command! ScribeOpen lua require("scribe").open()
command! ScribeClose lua require("scribe").close()
command! ScribeToggle lua require("scribe").toggle()
command! ScribeLine lua require("scribe").line()
command! -range ScribeRange <line1>,<line2>lua require("scribe").range()
